name: ci
on: [pull_request]
permissions:
  contents: 'read'
  pull-requests: 'read'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.19"
          reporter: github-pr-review
          fail_on_error: true
          golangci_lint_version: "latest"
          golangci_lint_flags: "--config=golangci.yaml"
          cache: false

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Test
        run: go test -v ./...
