name: ci
on: [pull_request]
permissions:
  contents: 'read'
  pull-requests: 'read'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reviewdog/action-golangci-lint@v2
        with:
          go_version: "1.19"
          reporter: github-pr-review
          fail_on_error: true
          golangci_lint_version: "latest"
          golangci_lint_flags: "--config=golangci.yaml"
          cache: false
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          args: --config=golangci.yml --issues-exit-code=0
          only-new-issues: true
          skip-cache: true
          install-mode: "binary"

  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Test
        run: go test -v ./...
